version: "3.7"

services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: "bitnami/kafka:latest"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  kafka_admin:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "9002:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=host.docker.internal:9092
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
  producer:
    container_name: "producer"
    build: ./producer
    volumes: 
      - ./producer:/producer
    ports:
      - 8080:8080
    command: /bin/sh -c "yarn && yarn start"
  consumer:
    container_name: "consumer"
    build: ./consumer
    volumes: 
      - ./consumer:/consumer
    command: /bin/sh -c "yarn && yarn start"
  elastic_search:
    image:  docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elastic_search
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - KIBANA_PASSWORD=teste123
      - ELASTIC_PASSWORD=teste123

volumes:
  es_data:
    driver: local